# Generated by Django 4.1 on 2022-08-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('login', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('validado', models.BooleanField(default=False)),
                ('aval', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MobiCampus.usuario')),
                ('permissao', models.BooleanField()),
            ],
            bases=('MobiCampus.usuario',),
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MobiCampus.usuario')),
                ('cnh', models.CharField(max_length=11)),
            ],
            bases=('MobiCampus.usuario',),
        ),
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('motorista_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MobiCampus.motorista')),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('rota', models.CharField(max_length=150)),
                ('custo', models.IntegerField()),
                ('finalizada', models.BooleanField(default=False)),
                ('passageiros', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0)),
            ],
            bases=('MobiCampus.motorista',),
        ),
    ]
